const C = {
	ALL_SETTINGS: "ALL_SETTINGS",
	GET_SETTING: "GET_SETTING",
	ADD_SETTING: "ADD_SETTING",
	EDIT_SETTING: "EDIT_SETTING",
	REMOVE_SETTING: "REMOVE_SETTING",
	ALL_POSTS: "ALL_POSTS",
	GET_POST: "GET_POST",
	ADD_POST: "ADD_POST",
	EDIT_POST: "EDIT_POST",
	REMOVE_POST: "REMOVE_POST",
	ALL_CATEGORIES: "ALL_CATEGORIES",
	GET_CATEGORY: "GET_CATEGORY",
	ADD_CATEGORY: "ADD_CATEGORY",
	EDIT_CATEGORY: "EDIT_CATEGORY",
	REMOVE_CATEGORY: "REMOVE_CATEGORY",
	ALL_USERS: "ALL_USERS",
	GET_USER: "GET_USER",
	ADD_USER: "ADD_USER",
	EDIT_USER: "EDIT_USER",
	REMOVE_USER: "REMOVE_USER",
	ALL_PROJECTS: "ALL_PROJECTS",
	GET_PROJECT: "GET_PROJECT",
	ADD_PROJECT: "ADD_PROJECT",
	EDIT_PROJECT: "EDIT_PROJECT",
	REMOVE_PROJECT: "REMOVE_PROJECT"
}

export default C;